### ISSUE TITLE
Wrong process.h included: '_getpid': identifier not found

### ISSUE THREAD

**Issue by dzenanz** [PlusToolkit/PlusLib#361]
Current master, fresh build, using fully updated VS2017, x64 target. The exact error message:
`c:\dev\plusgit\bin64s\pluslib\src\pluscommon\windowsaccuratetimer.h(135): error C3861: '_getpid': identifier not found`. Trying to look at `<process.h>` took me to `c:\Dev\PlusGit\bin64s\Deps\vtk-bin\Utilities\KWSys\vtksys\Process.h`, which probably means its include path comes before system path so it shadows the one in Windows 10 SDK.

**Comment by Sunderlandkyl** [comment]
I'm compiling a fresh build of VS2017 now. Hopefully I'll encounter the error and try to fix it.

I'll add a VS2017 build to the dashboard starting tomorrow as well to help catch some of these issues earlier.

**Comment by dzenanz** [comment]
I forgot to mention I selected VTK 8.1.0. It might matter, as the offending Process.h comes from VTK's KWSys.

**Comment by Sunderlandkyl** [comment]
The build that I started succeeded, but that was with VTK 7.1.0.
I'll try again with 8.1.0.

**Comment by Sunderlandkyl** [comment]
Yup, happened with 8.1.0.

**Comment by lassoan** [comment]
Can you upgrade to at least 8.1.1? This issue is fixed there.
More info:
https://gitlab.kitware.com/utils/kwsys/merge_requests/88
https://gitlab.kitware.com/vtk/vtk/issues/17292

**Comment by dzenanz** [comment]
I just selected the "middle" version option in PlusBuild. Just updating 8.1.0 there to 8.1.1 should do the trick.

**Comment by dzenanz** [comment]
Meanwhile I was  working with VTK 7.1 and VS2015.

**Comment by Sunderlandkyl** [comment]
The VTK8 version has been updated to 8.1.1, and compiles successfully.
